name: fixynergy
dependencies:
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - cudatoolkit=11.3
  - pandas
  - pyarrow
  - matplotlib
  - conda-forge::umap-learn
  - conda-forge::ipykernel
